name: LinearB

on:
  push:
    tags: ["*.*.*"]

jobs:
  linearb:
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: 'release'
    secrets: inherit
